### ISSUE TITLE
Specific route in express

### ISSUE THREAD

**Issue by tojacob** [errorception/staticify#15]
**I would like to indicate a route for all static files and their subfolders.**

To be able to access the assets from the route: 'domain.com/public/file.css'

Example:
```javascript
app.use('/public', staticify.middleware);
```

However, by doing this, the 'getVersionedPath' method no longer works correctly.

I have browsed the code and modified it a bit, adding 'route' in the staticify options.

Example:
```javascript
staticify(path.join(__dirname, './public'), { route: '/public' })
```

And I added this value in the 'buildVersionHash' method  on line 57:
```javascript
vers[`${opts.route}/${path.posix.relative(root, filePath)}`] = hash;
```

In this way the express route worked.

I know that validations were missing and possibly not the best way to do it, but I share it in case in the future they could officially include this possibility.

**Thanks for staticify!**

**Comment by rakeshpai** [comment]
Thanks for stopping by, @tojacob 

If you are interested, you could submit a PR for this change, and either @XhmikosR or I will gladly review. Happy to discuss if you want to first hash out the best way to implement this.

**Comment by tojacob** [comment]
Very good, I'll do that. @rakeshpai

**Comment by rakeshpai** [comment]
Closing this. See #18

**Comment by XhmikosR** [comment]
@rakeshpai: no need to close this before the PR is merged; I already reference it there, so when the PR is merged the issue will be closed.

**Comment by rakeshpai** [comment]
> when the PR is merged the issue will be closed
Didn't know that. :+1:
