### ISSUE TITLE
Setup help

### ISSUE THREAD

**Issue by benmccann** [errorception/staticify#35]
Do I still include `express.static` via `app.use` or does `staticify.middleware` replace it?

Also, I found the library via [this article](https://matthewsmith.io/blog/how-to-set-up-cache-busting-in-express) on Google and it does the following to strip the hash out:
```
app.use(function(req, res, next) {
  req.url = req.url.replace(/\/([^\/]+)\.[0-9a-f]+\.(css|js|jpg|png|gif|svg)$/, '/$1.$2');
  next();
});
app.use(express.static(path.join(__dirname, 'public'), { maxAge: '30 days' }));
```

I don't see that being done in the docs here. Under what circumstances would it be necessary?

**Comment by benmccann** [comment]
@matthewsmith-io thanks for the [great article](https://matthewsmith.io/blog/how-to-set-up-cache-busting-in-express). Including you here both for feedback and in case you can help

**Comment by rakeshpai** [comment]
I'm a little out of touch, so @XhmikosR can correct me if I'm mistaken.

> Do I still include express.static via app.use or does staticify.middleware replace it?

staticify.middleware replaces express.static, to set more aggressive caching headers.

> I don't see that being done in the docs here. Under what circumstances would it be necessary?

It shouldn't be necessary when you're using the middleware. The middleware handles this for you. [This](https://github.com/errorception/staticify#with-expressjs) is all you should need to do to get both the far-futures expires headers, and the stripping of the hash from the path. You should only need to do the manual handling described in the article if you aren't using the middleware.

**Comment by benmccann** [comment]
Thanks! I got it working.
