### ISSUE TITLE
Enable GitHub Actions

### ISSUE THREAD

**Issue by XhmikosR** [errorception/staticify#38]
@rakeshpai: can you sign up for https://github.com/features/actions ? We could then try ditching Travis CI.

**Comment by rakeshpai** [comment]
Done. GH says I've been added to the queue.

**Comment by XhmikosR** [comment]
Thanks. I made [a branch](https://github.com/errorception/staticify/compare/gh-actions) to test when this is enabled.

**Comment by rakeshpai** [comment]
Hey. I just got an email saying I have access to Actions. I’m mostly afk, but let me know if there’s anything I can do to get going.

**Comment by XhmikosR** [comment]
I don't see it enabled for the repo, can you check the repo options?

**Comment by XhmikosR** [comment]
@rakeshpai: did you make sure that you registered the errorception account and not just your personal account?

**Comment by rakeshpai** [comment]
I had signed up for my personal account, sorry. Signed up for Errorception now. It's instant activation now, so Actions is enabled for this project. Let me know if I can help in any way.
