### ISSUE TITLE
Add lgtm.com?

### ISSUE THREAD

**Issue by XhmikosR** [errorception/staticify#42]
@rakeshpai I was wondering what you think about lgtm.com? It was recently acquired by GitHub and I find it useful in some cases.

For example https://lgtm.com/projects/g/errorception/staticify/alerts?mode=list

**Comment by rakeshpai** [comment]
Looks good to me!

**Comment by XhmikosR** [comment]
Then go ahead and add it https://lgtm.com/projects/g/errorception/staticify/ci/

BTW, maybe you could fix the error too? It seems in our serve function we should handle `res` and `next`, right?

I'll add the badge afterwards.

**Comment by rakeshpai** [comment]
I've added LGTM.

Could you fix the code though? I'm not on a machine that I can checkout the code on. It looks like serve should only be called with req. res/next isn't needed. serve only accepts one arg.

**Comment by XhmikosR** [comment]
I'm not actually using this myself so I don't feel confident changing this part. No hurry, just don't forget about it :)
