### ISSUE TITLE
Does not seem to work on Windows

### ISSUE THREAD

**Issue by XhmikosR** [errorception/staticify#5]
Hi there.

So, I was trying to get this to work, but I'm on Windows so I always end up with the file I'm passing in `getVersionedPath`.

So basically I don't get any matches here:

https://github.com/errorception/staticify/blob/5606526a223dc446a6b0d77d4011d3c9af148d9e/index.js#L53

**Comment by rakeshpai** [comment]
Hey! Thanks for reporting the issue.

While I've taken care to make sure things work on Windows, I don't actually have a windows machine to test stuff on. If you can identify the issue and send a PR, I'll be glad to merge it in. Considering that things should be most-of-the-way working in Windows, it's probably something trivial causing it to break.

**Comment by XhmikosR** [comment]
I think I fixed it, I'll make a PR, but please add Travis and AppVeyor (for Windows).
